name: r_flutter
version: 0.6.0
description: Generate constants for resources which require using them as a String like fonts and assets.

homepage: https://github.com/timfreiheit/r_flutter
environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  args: '>=0.12.1 <2.0.0'
  dart_style: ^1.0.0
  path: '>=0.9.0 <2.0.0'
  yaml: ^2.1.15
  recase: ^2.0.1
  build: ^1.1.4
  build_config: ^0.4.0
  mustache: ^1.1.1
  json_annotation: any

dev_dependencies:
  test: any
  build_test: any
  lint: ^1.0.0

  build_runner: any
  json_serializable: any
